export const planeTicket = [
  {
    id: 1,
    name: "بویینک 737",
    logo: "/image/SahaAir.svg",
    campony: "ساها ایر",
    start: "00:45",
    finish: "02:10",
    available: true,
    capicity: 9,
    price: 3402500,
  },
  {
    id: 2,
    name: "فوکر 100",
    logo: "/image/Aseman.svg",
    campony: "آسمان",
    start: "06:00",
    finish: "07:25",
    available: false,
    capicity: 0,
    price: 3402500,
  },
  {
    id: 3,
    name: "بی آیی 106",
    logo: "/image/Mahan.svg",
    campony: "ماهان",
    start: "11:45",
    finish: "13:10",
    available: true,
    capicity: 2,
    price: 4402500,
  },
];

export const hotelList = [
  {
    imageSrc: [
      "/image/hotel1.jpg",
      "/image/hotel2.jpg",
      "/image/hotel3.jpg",
      "/image/hotel4.jpg",
    ],
    name: "هتل ساسان",
    star: 2,
    rate: 7.8,
    info: "قیمت یک شب اتاق دو تخته",
    price: 1444000,
    location: "خیابان ساسانی",
    off: 31,
  },
  {
    imageSrc: [
      "/image/chamran1.jpg",
      "/image/chamran2.jpg",
      "/image/chamran3.jpg",
      "/image/chamran4.jpg",
    ],
    name: "هتل چمران",
    star: 5,
    rate: 4.98,
    info: "قیمت یک شب اتاق دو تخته",
    price: 1944000,
    location: "خیابان شهید چمران",
    off: 0,
  },
  {
    imageSrc: [
      "/image/parsian1.jpg",
      "/image/parsian2.jpg",
      "/image/parsian3.jpg",
      "/image/parsian4.jpg",
    ],
    name: "هتل پارسیان",
    star: 3,
    rate: 8.5,
    info: "قیمت یک شب اتاق دو تخته",
    price: 1244000,
    location: "خیایان زند",
    off: 27,
  },
];

export const trainTicket = [
  {
    id: 1,
    name: "4 ستاره سالنی پردیس",
    logo: "/image/rejaTrain.svg",
    campony: "رجا",
    start: "00:45",
    finish: "02:10",
    available: true,
    capicity: 9,
    price: 3402500,
  },
  {
    id: 2,
    name: "5 ستاره اکونومی پلاس",
    logo: "/image/trainFadak.svg",
    campony: "فدک",
    start: "06:00",
    finish: "07:25",
    available: false,
    capicity: 0,
    price: 3402500,
  },
  {
    id: 3,
    name: "3 ستاره 6 تخته کویر",
    logo: "/image/trainChopar.svg",
    campony: "چوپار",
    icon: <smallTrain width={18} height={16} color="currentColor" />,
    start: "11:45",
    finish: "13:10",
    available: true,
    capicity: 2,
    price: 4402500,
  },
];

export const busTicket = [
  {
    id: 1,
    name: "درسا VIP مانیتور دار ",
    logo: "/image/gityPeyma.svg",
    campony: "گیتی پیما",
    start: "00:45",
    finish: "02:10",
    available: true,
    capicity: 9,
    price: 3402500,
  },
  {
    id: 2,
    name: "رویال VIP مانیتور دار + تخت ویبراتور",
    logo: "/image/royalSafar.svg",
    campony: "رویال سفر",
    start: "06:00",
    finish: "07:25",
    available: false,
    capicity: 0,
    price: 3402500,
  },
  {
    id: 3,
    name: "VIP مانیتور دار 3 ستاره",
    logo: "/image/gityPeyma.svg",
    campony: "گیتی پیما",
    start: "11:45",
    finish: "13:10",
    available: true,
    capicity: 2,
    price: 4402500,
  },
];
